- front-end/world-wide-map/src/components/Card.jsx
- front-end/world-wide-map/src/pages/WorldMap.jsx
- WorldMap.jsx에 카드 전환을 위한 버튼을 수정했습니다.
- Grid와 Flex styled-components를 사용해 카드 컴포넌트 간격을 수정했습니다.
> refactor: WorldMap.jsx 카드 전환 버튼 및 크기 수정, Grid 간격 수정

- front-end/world-wide-map/src/pages/WorldMap.jsx
- front-end/world-wide-map/src/utils/getCountryFlag.js
- `getCountryFlag.js` 신규 국가 국기 이모티콘 추가 진행
- RedDot hover의 경우 동작 기능 추가
- 마우스 포인터 모양 변경
- hover시, 말풍선 등장
- 기사 제목과, 국기 이모티콘을 말풍선에 나오게 수정
- blinkAnimation 멈춤 기능 추가
> feat: RedDot 마우스 hover의 경우 동작 기능 추가

- front-end/world-wide-map/src/components/Card.jsx
- front-end/world-wide-map/src/components/FirstModal.jsx
- front-end/world-wide-map/src/components/Modal.jsx
- front-end/world-wide-map/src/components/SecondModal.jsx
- front-end/world-wide-map/src/pages/Home.jsx
- front-end/world-wide-map/src/pages/WorldMap.jsx
> refactor: merge 충돌 해결

- front-end/world-wide-map/src/pages/Home.jsx
- front-end/world-wide-map/src/pages/WorldMap.jsx
- Home 화면 소개멘트 변경 및 버튼의 크기를 수정했습니다.
- WorldMap.jsx의 RedDot 상단의 느낌표를 각 나라의 이모지로 수정했습니다.
> fix: Home 화면 멘트 수정 및 WorldMap 이모지 변경

- front-end/world-wide-map/src/components/Detail.jsx
- front-end/world-wide-map/src/pages/WorldMap.jsx
- WorldMap 이미지 크기를 수정해 모바일에서 버튼 컴포넌트가 이미지 밖으로 탈출하는 이슈를 해결했습니다.
- Detail.jsx 에서 react-icons 를 로딩하는 시간이 길어지는 현상을 막기 위해 이모지를 사용하고, inline-style의 flex를 스타일 컴포넌트로 분리했습니다.
> fix: 레이아웃 해결 및 Detail.jsx 수정

- front-end/world-wide-map/src/components/FirstModal.jsx
- video 자동재생 필수 요소 3가지를 넣지 않아서 발생한 이슈로 확인
-  video 태그 속성으로 다음과 같은 속성 추가
1. autoplay
2. muted
3. playsinline
> fix: 모바일 환경 접속 시, FirstModal 속 영상 자동 전체화면 이슈 수정

- front-end/world-wide-map/public/index.html
- pubulic 폴더의 index.html의 favicon과 meta태그를 수정했습니다.
> fix: public 폴더 index.html의 파비콘, og 수정

- front-end/world-wide-map/public/index.html
- front-end/world-wide-map/src/components/FirstModal.jsx
- FirstModal.jsx의 autoPlay 와 playsInline 속성을 수정했습니다.
- index.html의 파비콘 경로를 수정했습니다.
> fix: video 태그 수정 및 파비콘 경로 수정

- front-end/world-wide-map/package.json
- front-end/world-wide-map/public/index.html
- front-end/world-wide-map/src/components/FirstModal.jsx
- package.json의 scripts에 deploy 스크립트를 추가했습니다.
- favicon이 나오지 않는 오류를 수정했습니다.
- FirstModal.jsx 의 video 태그의 속성을 수정했습니다.
> feat: deploy 스크립트 추가 및 파비콘 추가, 모바일 자동재생 이슈 해결

- front-end/world-wide-map/src/pages/WorldMap.jsx
##개요
- 넓은 디바이스에서 지도 사진이 짤리는 이슈를 해결했습니다.
> fix: WorldMap 사이즈 및 Flex 수정

- front-end/world-wide-map/src/components/Detail.jsx
- front-end/world-wide-map/src/pages/WorldMap.jsx
> feat: Detail 페이지 조회수 기능 추가

- front-end/world-wide-map/src/components/Detail.jsx
> feat: 디테일 페이지 버튼 추가

- front-end/world-wide-map/src/pages/WorldMap.jsx
- fix: Card 컴포넌트 데이터 랜덤 출력 기능 추가 - resolve #86
> fix: Card 컴포넌트 데이터 랜덤 출력 기능 추가 - resolve #86

- front-end/world-wide-map/src/pages/WorldMap.jsx
- Background-image의 width를 100vw로 수정했습니다.
> fix: 모바일 디바이스 대응

- front-end/world-wide-map/src/components/Detail.jsx
- front-end/world-wide-map/src/pages/WorldMap.jsx
- Detail.jsx 에 뒤로가기 버튼을 추가했습니다.
> feat: Detail.jsx 뒤로가기 버튼 추가

- front-end/world-wide-map/.gitignore
- front-end/world-wide-map/src/service/getNewsData.js
- front-end/world-wide-map/src/service/postRequest.js
- API 서버 주소를 .env 파일과 gitignore를 사용해 은닉했습니다.
> refactor: .env 파일 gitignore에 추가

- front-end/world-wide-map/src/service/postRequest.js
> Hofix: apiUrl 수정

- front-end/world-wide-map/src/pages/WorldMap.jsx
- 모바일 환경에서 화면이 짤려 나오는 이슈를 해결했습니다.
> Hotfix: 모바일 대응

- front-end/world-wide-map/src/pages/WorldMap.jsx
- 17인치 데스크톱과 모바일 양쪽에서의 반응형 이슈를 해결했습니다.
> Hotfix: 반응형 수정

- front-end/world-wide-map/src/pages/WorldMap.jsx
- 1800px 이상 디바이스에서의 반응형 레이아웃을 수정했습니다.
> fix: 대형 디바이스 반응형 수정

- front-end/world-wide-map/src/components/Card.jsx
> design: pointer 추가
